%% DFA para Security Violation
stateDiagram-v2
	[*] --> q0
	q0 --> q1: CR
	q0 --> q0: OTR
	q1 --> q2: ESC
	q1 --> q1: CR, TC
	q2 --> q2: *

	classDef accept fill:#cfc,stroke:#090,stroke-width:2px;
	class q2 accept;
	note right of q0: CR = HARDCODED_PASSWORD, API_KEY, HARDCODED_API_KEY\nESC = PRINT_CALL, IP_ADDRESS, SUSPICIOUS_URL\nTC = TODO_COMMENT\nOTR = otras etiquetas de ALL_LABELS\n* = cualquier etiqueta
